/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Waypoint = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
  'timestamp' : IDL.Int,
  'sequence' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const PlotInput = IDL.Record({
  'name' : IDL.Text,
  'waypoints' : IDL.Vec(Waypoint),
  'notes' : IDL.Text,
});
export const PlotId = IDL.Nat;
export const PlotStatus = IDL.Variant({
  'complete' : IDL.Null,
  'draft' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Plot = IDL.Record({
  'id' : PlotId,
  'status' : PlotStatus,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'waypoints' : IDL.Vec(Waypoint),
  'updatedAt' : Timestamp,
  'notes' : IDL.Text,
  'areaSqm' : IDL.Float64,
  'perimeterM' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createPlot' : IDL.Func([PlotInput], [PlotId], []),
  'deletePlot' : IDL.Func([PlotId], [], []),
  'exportPlot' : IDL.Func([PlotId], [IDL.Opt(Plot)], ['query']),
  'getPlot' : IDL.Func([PlotId], [IDL.Opt(Plot)], ['query']),
  'listPlots' : IDL.Func([], [IDL.Vec(Plot)], ['query']),
  'saveDraftPlot' : IDL.Func([PlotInput], [PlotId], []),
  'updatePlot' : IDL.Func([PlotId, PlotInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Waypoint = IDL.Record({
    'lat' : IDL.Float64,
    'lon' : IDL.Float64,
    'timestamp' : IDL.Int,
    'sequence' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const PlotInput = IDL.Record({
    'name' : IDL.Text,
    'waypoints' : IDL.Vec(Waypoint),
    'notes' : IDL.Text,
  });
  const PlotId = IDL.Nat;
  const PlotStatus = IDL.Variant({ 'complete' : IDL.Null, 'draft' : IDL.Null });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Plot = IDL.Record({
    'id' : PlotId,
    'status' : PlotStatus,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'waypoints' : IDL.Vec(Waypoint),
    'updatedAt' : Timestamp,
    'notes' : IDL.Text,
    'areaSqm' : IDL.Float64,
    'perimeterM' : IDL.Float64,
  });
  
  return IDL.Service({
    'createPlot' : IDL.Func([PlotInput], [PlotId], []),
    'deletePlot' : IDL.Func([PlotId], [], []),
    'exportPlot' : IDL.Func([PlotId], [IDL.Opt(Plot)], ['query']),
    'getPlot' : IDL.Func([PlotId], [IDL.Opt(Plot)], ['query']),
    'listPlots' : IDL.Func([], [IDL.Vec(Plot)], ['query']),
    'saveDraftPlot' : IDL.Func([PlotInput], [PlotId], []),
    'updatePlot' : IDL.Func([PlotId, PlotInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };