/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Plot {
  'id' : PlotId,
  'status' : PlotStatus,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'waypoints' : Array<Waypoint>,
  'updatedAt' : Timestamp,
  'notes' : string,
  'areaSqm' : number,
  'perimeterM' : number,
}
export type PlotId = bigint;
export interface PlotInput {
  'name' : string,
  'waypoints' : Array<Waypoint>,
  'notes' : string,
}
export type PlotStatus = { 'complete' : null } |
  { 'draft' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface Waypoint {
  'lat' : number,
  'lon' : number,
  'timestamp' : bigint,
  'sequence' : bigint,
  'accuracy' : number,
}
export interface _SERVICE {
  'createPlot' : ActorMethod<[PlotInput], PlotId>,
  'deletePlot' : ActorMethod<[PlotId], undefined>,
  'exportPlot' : ActorMethod<[PlotId], [] | [Plot]>,
  'getPlot' : ActorMethod<[PlotId], [] | [Plot]>,
  'listPlots' : ActorMethod<[], Array<Plot>>,
  'saveDraftPlot' : ActorMethod<[PlotInput], PlotId>,
  'updatePlot' : ActorMethod<[PlotId, PlotInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];