/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface PlotInput {
    name: string;
    waypoints: Array<Waypoint>;
    notes: string;
}
export type PlotId = bigint;
export interface Plot {
    id: PlotId;
    status: PlotStatus;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    waypoints: Array<Waypoint>;
    updatedAt: Timestamp;
    notes: string;
    areaSqm: number;
    perimeterM: number;
}
export interface Waypoint {
    lat: number;
    lon: number;
    timestamp: bigint;
    sequence: bigint;
    accuracy: number;
}
export enum PlotStatus {
    complete = "complete",
    draft = "draft"
}
export interface backendInterface {
    createPlot(input: PlotInput): Promise<PlotId>;
    deletePlot(plotId: PlotId): Promise<void>;
    exportPlot(plotId: PlotId): Promise<Plot | null>;
    getPlot(plotId: PlotId): Promise<Plot | null>;
    listPlots(): Promise<Array<Plot>>;
    saveDraftPlot(input: PlotInput): Promise<PlotId>;
    updatePlot(plotId: PlotId, input: PlotInput): Promise<void>;
}
import type { Plot as _Plot, PlotId as _PlotId, PlotStatus as _PlotStatus, Timestamp as _Timestamp, UserId as _UserId, Waypoint as _Waypoint } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createPlot(arg0: PlotInput): Promise<PlotId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlot(arg0);
            return result;
        }
    }
    async deletePlot(arg0: PlotId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlot(arg0);
            return result;
        }
    }
    async exportPlot(arg0: PlotId): Promise<Plot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.exportPlot(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportPlot(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlot(arg0: PlotId): Promise<Plot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlot(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlot(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPlots(): Promise<Array<Plot>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlots();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlots();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDraftPlot(arg0: PlotInput): Promise<PlotId> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDraftPlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDraftPlot(arg0);
            return result;
        }
    }
    async updatePlot(arg0: PlotId, arg1: PlotInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlot(arg0, arg1);
            return result;
        }
    }
}
function from_candid_PlotStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlotStatus): PlotStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Plot_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Plot): Plot {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Plot]): Plot | null {
    return value.length === 0 ? null : from_candid_Plot_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlotId;
    status: _PlotStatus;
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    waypoints: Array<_Waypoint>;
    updatedAt: _Timestamp;
    notes: string;
    areaSqm: number;
    perimeterM: number;
}): {
    id: PlotId;
    status: PlotStatus;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    waypoints: Array<Waypoint>;
    updatedAt: Timestamp;
    notes: string;
    areaSqm: number;
    perimeterM: number;
} {
    return {
        id: value.id,
        status: from_candid_PlotStatus_n4(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        waypoints: value.waypoints,
        updatedAt: value.updatedAt,
        notes: value.notes,
        areaSqm: value.areaSqm,
        perimeterM: value.perimeterM
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    complete: null;
} | {
    draft: null;
}): PlotStatus {
    return "complete" in value ? PlotStatus.complete : "draft" in value ? PlotStatus.draft : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Plot>): Array<Plot> {
    return value.map((x)=>from_candid_Plot_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
